spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:    #开发环境
    name: microservicecloud-config-cgh-dev
---
spring:
  profiles: test   #测试环境
  application:
    name: microservicecloud-config-cgh-test
#请保存为UTF-8格式
